"use client";

import { useState, useRef } from "react";
import jsPDF from "jspdf";

export default function LoanStatusPage() {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState("");

  const printRef = useRef<HTMLDivElement>(null);

  const checkStatus = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    setResult(null);

    try {
      const res = await fetch(`/api/loan-status?email=${email}`);
      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Something went wrong");
      } else {
        setResult(data);
      }
    } catch {
      setError("Network error. Please try again.");
    }

    setLoading(false);
  };

  // PRINT FUNCTION
  const handlePrint = () => {
    window.print();
  };

  // DOWNLOAD PDF FUNCTION (LETTERHEAD + WATERMARK)
  const handleDownloadPDF = () => {
    if (!result) return;

    const pdf = new jsPDF("p", "mm", "a4");

    // SACCO Logo
    const logo = "/sacco-logo.png";

    // Add logo
    pdf.addImage(logo, "PNG", 15, 10, 25, 25);

    // SACCO Letterhead
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);
    pdf.text("SACCO Smart Systems", 45, 22);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);
    pdf.text("Official Loan Status Document", 45, 30);
    pdf.text("Generated by SACCO Loan Portal", 45, 36);

    // Divider
    pdf.setLineWidth(0.5);
    pdf.line(15, 42, 195, 42);

    // ⭐ WATERMARK ⭐
    pdf.setFontSize(60);
    pdf.setTextColor(200, 200, 200);
    pdf.setFont("helvetica", "bold");
    pdf.text("SACCO", 35, 150, { angle: 45 });

    // Reset text color
    pdf.setTextColor(0, 0, 0);

    // Loan Details Section
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Loan Status Details", 15, 55);

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");

    let y = 65;

    const addLine = (label: string, value: any) => {
      pdf.text(`${label}: ${value}`, 15, y);
      y += 8;
    };

    addLine("Status", result.status);
    addLine("Full Name", result.full_name);
    addLine("Email", result.email);
    addLine("Loan Amount", `KES ${result.loan_amount}`);
    addLine("Purpose", result.purpose);
    addLine("Risk Score", result.risk_score);
    if (result.guardian_reason) addLine("Reason", result.guardian_reason);
    addLine("Timestamp", result.timestamp);

    // Footer
    pdf.setFontSize(10);
    pdf.text(
      "This document is system-generated and valid without a signature.",
      15,
      285
    );

    pdf.save("loan-details.pdf");
  };

  return (
    <div className="min-h-screen bg-sacco-bg p-6 flex items-center justify-center">
      <div className="w-full max-w-md bg-white p-8 rounded-xl shadow-xl border border-sacco-blue/20">

        {/* Logo */}
        <div className="flex flex-col items-center mb-4">
          <img src="/sacco-logo.png" alt="SACCO Logo" className="h-16 w-auto opacity-90" />
          <h2 className="text-sacco-blue font-semibold text-lg mt-2 tracking-wide">
            SACCO Loans
          </h2>
        </div>

        <h1 className="text-3xl font-semibold text-sacco-blue mb-6 text-center">
          Check Loan Status
        </h1>

        {/* Form */}
        <form onSubmit={checkStatus} className="space-y-5">
          <div>
            <label className="block text-sm font-medium text-sacco-blue mb-1">
              Enter your email
            </label>
            <input
              type="email"
              placeholder="example@gmail.com"
              className="w-full border border-gray-300 p-3 rounded-lg text-gray-900
                         focus:border-sacco-blue focus:ring-1 focus:ring-sacco-blue 
                         outline-none transition"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>

          <button
            type="submit"
            className="w-full bg-sacco-blue text-white p-3 rounded-lg font-medium 
                       hover:bg-[#00264d] transition shadow-sm"
          >
            {loading ? "Checking..." : "Check Status"}
          </button>
        </form>

        {/* Error */}
        {error && (
          <p className="text-red-600 text-center mt-4 font-medium">{error}</p>
        )}

        {/* Result */}
        {result && (
          <div ref={printRef} className="mt-6 p-5 rounded-xl border shadow bg-sacco-bg text-gray-900">

            {/* APPROVED */}
            {result.status === "APPROVED" && (
              <div>
                <h2 className="text-xl font-bold text-green-700 mb-3">
                  ✔ Loan Approved
                </h2>

                <p><strong>Name:</strong> {result.full_name}</p>
                <p><strong>Email:</strong> {result.email}</p>
                <p><strong>Amount:</strong> KES {result.loan_amount}</p>
                <p><strong>Purpose:</strong> {result.purpose}</p>
                <p><strong>Risk Score:</strong> {result.risk_score}</p>
                <p><strong>Timestamp:</strong> {result.timestamp}</p>
              </div>
            )}

            {/* DECLINED */}
            {result.status === "DECLINED" && (
              <div>
                <h2 className="text-xl font-bold text-red-700 mb-3">
                  ✖ Loan Declined
                </h2>

                <p><strong>Name:</strong> {result.full_name}</p>
                <p><strong>Email:</strong> {result.email}</p>
                <p><strong>Amount:</strong> KES {result.loan_amount}</p>
                <p><strong>Purpose:</strong> {result.purpose}</p>
                <p><strong>Risk Score:</strong> {result.risk_score}</p>
                <p><strong>Reason:</strong> {result.guardian_reason}</p>
                <p><strong>Timestamp:</strong> {result.timestamp}</p>
              </div>
            )}

            {/* NO APPLICATION */}
            {result.status === "NO_APPLICATION" && (
              <div>
                <h2 className="text-xl font-bold text-gray-700 mb-3">
                  No Application Found
                </h2>
                <p className="text-gray-900">{result.message}</p>
              </div>
            )}
          </div>
        )}

        {/* PRINT + DOWNLOAD + BACK BUTTONS */}
        {result && (
          <div className="mt-4 flex flex-col gap-3">

            <div className="flex gap-3">
              <button
                onClick={handlePrint}
                className="w-1/2 bg-sacco-blue text-white p-2 rounded-lg font-medium hover:bg-[#00264d] transition"
              >
                Print
              </button>

              <button
                onClick={handleDownloadPDF}
                className="w-1/2 bg-sacco-gold text-sacco-blue p-2 rounded-lg font-medium hover:bg-[#e0a200] transition"
              >
                Download PDF
              </button>
            </div>

            <button
              onClick={() => window.location.href = "/dashboard"}
              className="w-full bg-gray-200 text-sacco-blue p-2 rounded-lg font-medium hover:bg-gray-300 transition"
            >
              Back to Dashboard
            </button>

          </div>
        )}

        <p className="text-center text-sm text-gray-500 mt-6">
          Powered by Michaela J Browers{" "}
          <span className="text-sacco-gold font-semibold">
            SACCO Smart Systems
          </span>
        </p>
      </div>
    </div>
  );
}